# Use official Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt flask

# Expose port
EXPOSE 5003

# Run app
CMD ["python", "app.py"]